// micro-frontends/vue/src/components/App.vue
<template>
  <div>
    <Container>
      <h1>
        Done
      </h1>
      <ItemList
        :items="items"
      />
    </Container>
  </div>
</template>

<script>
  import { mapState, } from 'vuex'
  import { styled, } from 'styletron-vue'
  import styletron from '../StyletronInstance'
  import ItemList from './ItemList'

  const Container = styled('div', {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    maxWidth: '768px',
    margin: '0 auto',
  })

  export default {
    name: 'App',
    computed: mapState({
      items: state => state.item.loadedItems,
    }),
    components: {
      ItemList,
      Container,
    },
    styletron,
  }
</script>

<style>
  @import '~normalize.css';
  @import '../assets/styles/global.css';
</style>

// micro-frontends/users/src/components/App/App.jsx
import * as React from 'react'
import * as PropTypes from 'prop-types'

import 'normalize.css'

import '../../assets/styles/global.css'

import UserList from '../UserList/UserList'
import { styled, } from 'styletron-react'

const Container = styled('div', {
  margin: '0 auto',
  maxWidth: '768px',
  padding: '0 1rem',
})

const App = (props) => {
  const {
    users = [],
    ...etcProps
  } = props

  return (
    <div
      {...etcProps}
    >
      <Container>
        <h1>
          Users
        </h1>
        <UserList
          items={users}
        />
      </Container>
    </div>
  )
}

App.propTypes = {
  users: PropTypes.arrayOf(PropTypes.shape({
    name: PropTypes.string,
    email: PropTypes.string,
  })),
}

export default App
