// micro-frontends/react/src/components/ItemList/ItemList.jsx
import * as React from 'react'
import * as PropTypes from 'prop-types'
import { styled, } from 'styletron-react'
import { Link, } from 'react-router-dom'

const ItemWrapper = styled(Link, {
  textDecoration: 'none',
  color: 'inherit',
})

const Item = styled('article', {
  border: '1px solid currentColor',
  margin: '1rem 0',
})

const ItemHeader = styled('header', {
  padding: '0 1rem',
  margin: '1rem 0',
})

const ItemTitle = styled('h2', {
  margin: 0,
  fontSize: '1em',
})

const ItemList = props => {
  const {
    items = [],
    itemKey,
    itemLink,
  } = props

  return (
    <React.Fragment>
      {
        items.map(item => (
          <ItemWrapper
            key={itemKey(item)}
            to={itemLink(item)}
          >
            <Item>
              <ItemHeader>
                <ItemTitle>
                  {item.title}
                </ItemTitle>
              </ItemHeader>
            </Item>
          </ItemWrapper>
        ))
      }
    </React.Fragment>
  )
}

ItemList.propTypes = {
  items: PropTypes.arrayOf(PropTypes.shape({
    title: PropTypes.string,
    description: PropTypes.string,
  })),
  itemKey: PropTypes.func,
  itemLink: PropTypes.func,
}

export default ItemList

// micro-frontends/vue/src/components/ItemList.vue
<template>
  <div>
    <ArticleBase
      v-for="item in items"
      v-bind:key="item.id"
    >
      <ArticleHeader>
        <ArticleTitle>
          {{item.title}}
        </ArticleTitle>
      </ArticleHeader>
    </ArticleBase>
  </div>
</template>

<script>
  import { styled, } from 'styletron-vue'

  const ArticleBase = styled('article', {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'currentColor',
    marginTop: '1rem',
    marginBottom: '1rem',
  })

  const ArticleHeader = styled('header', {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    marginTop: '1rem',
    marginBottom: '1rem',
  })

  const ArticleTitle = styled('h2', {
    marginTop: 0,
    marginBottom: 0,
    fontSize: '1em',
  })

  export default {
    name: 'ItemList',
    props: {
      items: Array,
    },
    components: {
      ArticleBase,
      ArticleHeader,
      ArticleTitle,
    },
  }
</script>
